/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Example: typeof import('./../views/example/index.vue')['default']
    Home: typeof import('./../views/home/index.vue')['default']
    HomeItem: typeof import('./../views/home/components/HomeItem.vue')['default']
    HomeView: typeof import('./../views/homeView/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
