/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeDisplay: typeof import('./../.vitepress/theme/components/CodeDisplay/index.vue')['default']
    CommonTable: typeof import('./../.vitepress/theme/components/CommonTable/index.vue')['default']
    DisplayLayout: typeof import('./../.vitepress/theme/components/DisplayLayout/index.vue')['default']
    Home: typeof import('./../.vitepress/theme/components/home.vue')['default']
    IconArrowRight: typeof import('./../.vitepress/theme/components/icons/iconArrowRight.vue')['default']
    IconSearch: typeof import('./../.vitepress/theme/components/icons/iconSearch.vue')['default']
    Layout: typeof import('./../.vitepress/theme/Layout.vue')['default']
    RawDisplay: typeof import('./../.vitepress/theme/components/RawDisplay/index.vue')['default']
    Theme: typeof import('./../.vitepress/theme/Theme.vue')['default']
    VCSearch: typeof import('./../.vitepress/theme/components/VCSearch.vue')['default']
    VDSimple: typeof import('./../.vitepress/theme/components/example/VDSimple.vue')['default']
    VDTwoLists: typeof import('./../.vitepress/theme/components/example/VDTwoLists.vue')['default']
    VPContent: typeof import('./../.vitepress/theme/components/VPContent.vue')['default']
    VPFlyout: typeof import('./../.vitepress/theme/components/VPFlyout.vue')['default']
    VPMenu: typeof import('./../.vitepress/theme/components/VPMenu.vue')['default']
    VPMenuGroup: typeof import('./../.vitepress/theme/components/VPMenuGroup.vue')['default']
    VPNav: typeof import('./../.vitepress/theme/components/VPNav.vue')['default']
    VPNavBar: typeof import('./../.vitepress/theme/components/VPNavBar.vue')['default']
    VPNavBarMenu: typeof import('./../.vitepress/theme/components/VPNavBarMenu.vue')['default']
    VPNavBarMenuGroup: typeof import('./../.vitepress/theme/components/VPNavBarMenuGroup.vue')['default']
  }
}
